name: CodeClimate Coverage

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened

jobs:
  codeclimate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v2.7.3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          workingDirectory: frontend
          coverageCommand: ./node_modules/nyc/bin/nyc.js --reporter=clover yarn test:watch --watchAll=false --coverage --maxWorkers 2 -u
          debug: true
