name: CodeClimate Coverage

on:
  push:
    branches:
      - develop
  workflow_dispatch: #for manual dispatch

jobs:
  codeclimate:
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Download cc-test-reporter binary
        run: |
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter

      - name: List folders
        run: |
          ls -la

      # - name: Install dependencies
      #   run: |
      #     cd frontend
      #     npm install

      # - name: Upload coverage to CodeClimate
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      #   run: |
      #     cd frontend
      #     ../tmp/cc-test-reporter before-build
      #     ./node_modules/nyc/bin/nyc.js --reporter=lcov --exclude=node_modules --exclude=frontend/public yarn test --maxWorkers 2 -u --silent
      #     ../tmp/cc-test-reporter format-coverage -t lcov -o "../coverage/codeclimate.react.coverage.frontend.json" ./frontend/coverage/lcov.info
      #     ../tmp/cc-test-reporter upload-coverage --debug --input ../coverage/codeclimate.react.coverage.frontend.json

      # - name: Code Climate after-build
      #   run: |
      #     ./tmp/cc-test-reporter after-build --exit-code $?
