name: Deploy to GCP

on:
  push:
    branches:
      - develop
  workflow_dispatch: #for manual dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  release-branch:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [deploy]
    env:
      GITHUB_JOB: release-branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release branch (conditional)
        run: |
          git reset --hard
          git switch -c release/${{ GITHUB.REF_NAME }}
          git push --set-upstream origin release/${{ GITHUB.REF_NAME }}