name: Deploy to GCP

on:
  release:
    types: [created]
  push:
    branches:
      - develop
  workflow_dispatch: #for manual dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: "read"
      contents: "read"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Define target environment
        run: |
          echo 'Branch is ${{ GITHUB.REF }}'

  release-branch:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    needs: [deploy]
    env:
      GITHUB_JOB: release-branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release branch (conditional)
        run: |
          git reset --hard
          git switch -c release/${{ GITHUB.REF_NAME }}
          git push --set-upstream origin release/${{ GITHUB.REF_NAME }}